name: "Audit logging"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    #TODO: if: github.repository_owner == 'NixOS'
    steps:
    - name: Analyze event.json
      run: jq 'with_entries(select([.key] | inside(["ref", "created", "deleted", "forced"])))' $GITHUB_EVENT_PATH | tee result.json
